name: EBAC CI Mobile

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      # Etapa 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      # Etapa 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Etapa 4: Rodar o comando para verificar as variáveis de ambiente
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "SAUCELABS_USERNAME=${{ secrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCELABS_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}" >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      # Etapa 5: Debug: Listar arquivos (opcional)
      - name: Debug files
        run: ls -R
        working-directory: ./config

      # Etapa 6: Rodar testes
      - name: Run tests
        run: npm test
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }} 
          SAUCELABS_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          EMAIL: ${{ vars.EMAIL }}
          PASSWORD: ${{ vars.PASSWORD }}
