name: EBAC CI Mobile

on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0' 


      - name: Install dependencies
        run: npm install

      - name: Debug files
        run: ls -R
        working-directory: ./config

      - name: Set environment variables
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          run: | 
            echo "Environment: $ENVIRONMENT"

      - name: Saucelabs Env
        env:
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
        run: |
          echo "Sauce Labs username: $SAUCELABS_USERNAME"
          echo "Sauce Labs access key: $SAUCELABS_ACCESS_KEY"

      - name: Run tests
        env:
          EMAIL: ${{ vars.EMAIL }}
          PASSWORD: ${{ vars.PASSWORD }}
        run: npm test
